#   Day - 11 , NumPy

NumPy arrays & the no-loop philosophy

NumPy stores data in contiguous C arrays. Operations happen in compiled Fortran/C — not Python loops. The golden rule: if you're looping, you're doing it wrong.




# NumPy - Core

In [1]:
print("HEllo World")

HEllo World


In [2]:
import numpy as np
import pandas as pd

### Array creation — real workflow patterns


In [3]:
arr = np.array([1,2,3],dtype=np.float32)
arr

array([1., 2., 3.], dtype=float32)

In [4]:
arr = np.array([1,2,3],dtype=np.int32)
arr

array([1, 2, 3], dtype=int32)

In [5]:
# Structured initialization
np.zeros(3)

array([0., 0., 0.])

In [6]:
np.zeros((3,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.zeros((3,2,5))


array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [8]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones((2, 5))         # all ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.eye(4)               # identity matrix


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
# np.arange(0,10,0.5) -> 0->10 step 0.5
np.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

### Random (set seed for reproducibility)


In [12]:
rng=np.random.default_rng(seed=42)
rng

Generator(PCG64) at 0x10A76AA40

In [13]:
rng.normal(0,1,(1000,768))

array([[ 0.30471708, -1.03998411,  0.7504512 , ..., -1.78361113,
         0.08362108, -0.55619196],
       [-1.27984096,  1.68181662,  1.72899534, ..., -1.1648281 ,
         2.00875539, -0.95942775],
       [ 0.74922293, -1.68734769, -0.93026469, ..., -0.89002075,
        -2.76267551, -0.43469947],
       ...,
       [-0.03100778, -0.79190681,  0.42016238, ..., -0.07965897,
        -0.16792131, -1.59124065],
       [-1.58472591,  2.3351624 , -0.24401136, ...,  0.17960714,
        -2.24351712,  0.33605373],
       [-0.13947304,  0.43859894,  0.69618025, ..., -0.93625414,
        -1.03291464, -0.11169594]], shape=(1000, 768))

In [21]:
np.random.randint(100)

15

In [22]:
np.random.rand()

0.19001967171228695

### Shape, strides & views — the memory model
Arrays have shape, dtype, and strides. Slices are views (no copy) — critical for performance and a common bug source.


In [25]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [26]:
a.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [28]:
a.shape

(24,)

In [29]:
a.strides

(8,)

In [30]:
a.dtype

dtype('int64')

In [31]:
a.ndim

1

# View vs copy — interview classic


In [33]:
rs=a.reshape(4,6)
rs

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [34]:
view=rs[1:3,:]
view

array([[ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [35]:
rs

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [37]:
copy=a[1:3].copy()
copy

array([1, 2])

In [38]:
rs

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [39]:
rs.T

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])

In [40]:
rs.T.strides

(8, 48)

### Vectorised ops — the no-loop way


In [41]:
# Element-wise arithmetic (no loop needed)
scores = np.array([85,92,78,96])
scores.sum()

np.int64(351)

In [43]:
normalised = (scores - scores.mean()) / scores.std()
normalised


array([-0.40033099,  0.61869335, -1.41935532,  1.20099297])

In [45]:
# Boolean masking (replaces if-loops)
high_scores = scores[scores > 90]  # [92, 96]
high_scores

array([92, 96])

### Universal functions (ufuncs) — compiled C, extremely fast


In [46]:
# Universal functions (ufuncs) — compiled C, extremely fast
np.sqrt(scores)

array([9.21954446, 9.59166305, 8.83176087, 9.79795897])

In [47]:
np.exp(normalised)

array([0.67009821, 1.85650065, 0.24186989, 3.32341533])

### Vectorised ops — the no-loop way


In [48]:
# Boolean masking (replaces if-loops)
high_scores = scores[scores > 90]  # [92, 96]
high_scores

array([92, 96])

In [50]:
# Universal functions (ufuncs) — compiled C, extremely fast
np.sqrt(scores)


array([9.21954446, 9.59166305, 8.83176087, 9.79795897])

In [51]:
np.exp(normalised)

array([0.67009821, 1.85650065, 0.24186989, 3.32341533])

In [52]:
np.log1p(scores)    # numerically stable log(1+x)

array([4.4543473 , 4.53259949, 4.36944785, 4.57471098])

## Axis-wise reductions


In [53]:
matrix = rng.random((100, 50))
matrix

array([[0.97822715, 0.12102412, 0.10202601, ..., 0.35433508, 0.53585029,
        0.00455675],
       [0.80457905, 0.73110973, 0.61299649, ..., 0.36432845, 0.82393721,
        0.02837223],
       [0.79378559, 0.46097033, 0.97779036, ..., 0.2934159 , 0.3239828 ,
        0.50727612],
       ...,
       [0.18770768, 0.22910658, 0.53698066, ..., 0.56963312, 0.35188413,
        0.82106349],
       [0.37909921, 0.79313603, 0.03096548, ..., 0.81421878, 0.79260423,
        0.91528438],
       [0.58229478, 0.74251781, 0.86091808, ..., 0.32891224, 0.90875302,
        0.64452077]], shape=(100, 50))

In [54]:
matrix.sum(axis=0)

array([56.06248824, 46.48080408, 52.4000269 , 51.1141104 , 55.32243469,
       48.27211283, 46.87022837, 49.63292689, 51.38635713, 54.83936522,
       46.43985194, 56.19802178, 45.32556171, 53.63146062, 45.40588113,
       49.8896677 , 56.39652988, 46.68596816, 52.32030997, 51.06503023,
       50.93755412, 51.52902162, 48.13393142, 46.90480084, 44.80953928,
       51.67787467, 45.95840608, 50.92482622, 51.59609729, 50.54794077,
       53.57491593, 45.45218988, 44.83161814, 42.96148431, 46.38593718,
       49.18814188, 52.97825038, 51.34434298, 53.98824638, 49.1515189 ,
       46.65849065, 49.73954837, 50.69351506, 50.13442629, 48.70701384,
       46.53087195, 52.50814307, 50.58158642, 51.38506168, 53.01664522])

In [55]:
matrix.sum(axis=0)

array([56.06248824, 46.48080408, 52.4000269 , 51.1141104 , 55.32243469,
       48.27211283, 46.87022837, 49.63292689, 51.38635713, 54.83936522,
       46.43985194, 56.19802178, 45.32556171, 53.63146062, 45.40588113,
       49.8896677 , 56.39652988, 46.68596816, 52.32030997, 51.06503023,
       50.93755412, 51.52902162, 48.13393142, 46.90480084, 44.80953928,
       51.67787467, 45.95840608, 50.92482622, 51.59609729, 50.54794077,
       53.57491593, 45.45218988, 44.83161814, 42.96148431, 46.38593718,
       49.18814188, 52.97825038, 51.34434298, 53.98824638, 49.1515189 ,
       46.65849065, 49.73954837, 50.69351506, 50.13442629, 48.70701384,
       46.53087195, 52.50814307, 50.58158642, 51.38506168, 53.01664522])

In [56]:
matrix.argmax(axis=1) # index of max per row

array([25, 41,  2, 49, 34,  6, 15, 35, 28, 42, 17, 33, 14, 26,  1, 18, 15,
        4, 22, 23, 42, 48, 42, 27, 19,  7,  7, 46, 21, 27, 43,  8, 37, 12,
       35, 44, 22, 47, 18, 26,  3, 34, 15, 38, 35, 13, 16, 29, 35, 37, 47,
        9,  0, 35,  2, 21, 33, 20, 25, 43,  3, 39, 13, 46, 37, 14,  0, 38,
       26,  8, 25,  9, 49,  2, 28, 38,  8, 13, 13,  4, 23, 40, 42, 27, 32,
       12, 45,  7, 32, 35, 21, 47, 28, 45, 18, 43, 11,  5, 21, 24])

Interview insight: "Why is NumPy faster than Python loops?" — Answer: numpy stores homogeneous data in contiguous memory and calls compiled C/Fortran routines. Python loops have per-iteration overhead: type checking, reference counting, bytecode interpretation. NumPy eliminates all of that.

# Broadcasting — the shape-matching superpower

- Broadcasting lets arrays of different shapes operate together without copying data. NumPy expands dimensions implicitly by the rules below.



### The 3 broadcasting rules
1. Pad dimensions on the left . If shapes have different number of dims, prefix 1s. Shape (3,) becomes (1, 3).
2. Expand size-1 dimensions
Any axis of size 1 is stretched to match the other array's size along that axis.
3. Sizes must match or be 1
If neither axis is 1 and sizes differ, you get a ValueError. No silent surprises.


Shape compatibility chart
A shape	B shape	Result shape	Works?
(3, 4)	(4,)	(3, 4)	yes
(3, 1)	(1, 4)	(3, 4)	yes
(3, 4)	(3,)	—	error
(1, 100, 1)	(32, 1, 768)	(32, 100, 768)	yes
(3, 4)	(3, 5)	—	error

In [66]:
# Pattern 1: Normalise each row independently
X = rng.random((1000, 20))  # 1000 samples, 20 features
mean = X.mean(axis=0)      # shape (20,)
std  = X.std(axis=0)       # shape (20,)
X_norm = (X - mean) / std    # broadcast: (1000,20)-(20,) → works!
X_norm

array([[ 0.40433986,  0.90734585, -0.19432277, ...,  0.14283988,
        -0.05830487, -1.53339217],
       [-1.38558719,  1.18312356, -1.31566867, ..., -1.66287316,
        -0.62565229,  1.64179792],
       [-0.74302361, -1.0172761 , -1.28515369, ...,  1.54510558,
         0.93967497,  1.53425337],
       ...,
       [ 1.66804103,  1.59448461,  0.9080478 , ...,  1.47510797,
         0.51674953, -1.61161768],
       [-0.9966431 , -0.60505368, -0.24194539, ..., -0.28101077,
         0.80291604,  0.75909502],
       [-1.55659708,  0.42702146, -0.47449742, ...,  0.18843376,
         0.00237936, -0.05778353]], shape=(1000, 20))

In [67]:
mean.shape

(20,)

In [68]:
# Pattern 2: Pairwise distance (no loop)
a = rng.random((100, 3))     # 100 points in 3D
b = rng.random((200, 3))     # 200 points in 3D
# a[:,None,:] → (100,1,3)  b[None,:,:] → (1,200,3)
diffs = a[:, None, :] - b[None, :, :]  # (100,200,3)
dists = np.sqrt((diffs**2).sum(axis=-1)) # (100,200)


In [69]:
a

array([[0.22533666, 0.397799  , 0.03577157],
       [0.00935938, 0.40126316, 0.32441731],
       [0.37268826, 0.36840971, 0.52643825],
       [0.40279896, 0.68144516, 0.57094185],
       [0.21766561, 0.59295613, 0.00627904],
       [0.47067888, 0.72657332, 0.53167084],
       [0.83490497, 0.34860753, 0.20818593],
       [0.36717871, 0.14316438, 0.90696114],
       [0.56841871, 0.63594914, 0.04683177],
       [0.14191122, 0.30446805, 0.30776531],
       [0.81722931, 0.44753579, 0.38120604],
       [0.41284563, 0.67883977, 0.72782362],
       [0.01919651, 0.26480041, 0.29417133],
       [0.70471112, 0.83926286, 0.07417383],
       [0.63186192, 0.39428199, 0.47956984],
       [0.25156746, 0.50937203, 0.17019038],
       [0.06222958, 0.42366818, 0.36072896],
       [0.58178409, 0.09829719, 0.05139154],
       [0.98121707, 0.29486776, 0.59022815],
       [0.89414852, 0.63147925, 0.24736085],
       [0.50266619, 0.5142564 , 0.02642392],
       [0.62069376, 0.63495159, 0.82875265],
       [0.

In [70]:
b

array([[1.00622035e-01, 9.50358039e-01, 5.66380447e-01],
       [4.50252934e-01, 5.09525395e-01, 4.05751714e-01],
       [1.73504738e-02, 2.99754892e-01, 1.33471182e-01],
       [8.92508722e-01, 4.65750108e-01, 3.29716632e-01],
       [9.16553074e-01, 2.97920105e-01, 3.98198148e-01],
       [1.11441184e-01, 9.92968560e-01, 5.24539805e-01],
       [6.19369731e-01, 5.42111113e-01, 5.80699600e-01],
       [3.53103684e-02, 3.51232054e-01, 4.90244153e-01],
       [4.67385051e-01, 8.02733929e-01, 1.60121163e-01],
       [5.84796651e-01, 4.01829906e-01, 6.53016703e-01],
       [5.47796938e-01, 2.37232091e-01, 8.33868468e-01],
       [7.57828760e-01, 4.20619013e-01, 6.05070499e-01],
       [9.09382415e-01, 7.38450639e-01, 7.79903933e-01],
       [2.21330760e-01, 7.06341739e-01, 1.71784716e-01],
       [7.17538000e-02, 1.76392697e-01, 6.54437107e-01],
       [2.01235952e-01, 2.88486173e-01, 4.50757562e-02],
       [6.06285304e-01, 5.60788820e-01, 8.82883373e-01],
       [4.81446465e-01, 3.19428

In [71]:
diffs

array([[[ 0.12471462, -0.55255904, -0.53060888],
        [-0.22491628, -0.11172639, -0.36998015],
        [ 0.20798618,  0.09804411, -0.09769961],
        ...,
        [-0.31175793,  0.33348773, -0.94395719],
        [ 0.2049786 , -0.56519287, -0.46161844],
        [-0.61733227,  0.25798677, -0.78728762]],

       [[-0.09126265, -0.54909487, -0.24196314],
        [-0.44089355, -0.10826223, -0.0813344 ],
        [-0.00799109,  0.10150827,  0.19094613],
        ...,
        [-0.5277352 ,  0.3369519 , -0.65531145],
        [-0.01099868, -0.5617287 , -0.17297269],
        [-0.83330955,  0.26145094, -0.49864188]],

       [[ 0.27206622, -0.58194833, -0.0399422 ],
        [-0.07756467, -0.14111569,  0.12068653],
        [ 0.35533779,  0.06865482,  0.39296706],
        ...,
        [-0.16440633,  0.30409844, -0.45329052],
        [ 0.3523302 , -0.59458216,  0.02904824],
        [-0.46998067,  0.22859748, -0.29662095]],

       ...,

       [[ 0.03349619, -0.3651696 ,  0.02353662],
        [-0

In [65]:
dists

array([[0.16678506, 0.77567283, 0.7399599 , ..., 1.00923232, 1.00729646,
        0.79694659],
       [1.09714425, 0.5745116 , 0.4403021 , ..., 0.64196367, 0.49043233,
        0.97228445],
       [0.42710746, 0.40476564, 0.53321533, ..., 0.53472263, 0.61293567,
        0.24271716],
       ...,
       [0.62314473, 0.44189417, 0.55015437, ..., 0.50894599, 0.48895088,
        0.24499611],
       [0.60237478, 0.57381007, 0.40939639, ..., 0.82187197, 0.77841929,
        0.90242086],
       [0.60343784, 0.10342722, 0.27600167, ..., 0.29363256, 0.35276885,
        0.35244467]], shape=(100, 200))

# Linear algebra — matmul, dot, norm, SVD

- NumPy delegates to BLAS/LAPACK — the same routines used in MATLAB. Understanding what these ops do geometrically is what interviewers test.



| Operation  | Use Case              | Batched? | Note                                    |
|------------|-----------------------|----------|-----------------------------------------|
| `np.dot`   | Dot product, matrix mult | no     | Avoid for **2D+ arrays**; semantics get confusing. |
| `@`/ `matmul` | Matrix × matrix, matrix × vector | yes  | **Preferred**. Works on stacks of matrices. |
| `np.einsum`| Any contraction you can describe | yes | Most expressive but slower if not optimized. |

In [78]:
A = rng.random((3, 4))
A

array([[0.27422816, 0.31791214, 0.13776071, 0.53257416],
       [0.9003258 , 0.9783281 , 0.90462313, 0.96262492],
       [0.32295309, 0.4828968 , 0.61092627, 0.58133899]])

In [79]:
B =rng.random((4,5))
B

array([[0.94567506, 0.73876592, 0.09373249, 0.05681499, 0.92269205],
       [0.46814597, 0.882807  , 0.9130514 , 0.74325685, 0.55104599],
       [0.48086649, 0.64602267, 0.74447538, 0.64828021, 0.90419198],
       [0.80303822, 0.07781565, 0.72446206, 0.12969513, 0.33013092]])

In [80]:
C=A@B
C

array([[0.90208193, 0.61368462, 0.80436344, 0.41025046, 0.72859367],
       [2.51744357, 2.18811924, 2.34850849, 1.4895981 , 2.50557246],
       [1.29208628, 1.1048009 , 1.3471584 , 0.84871318, 1.3083972 ]])

In [83]:
# Batched matmul — e.g. attention heads
Q = rng.random((8, 64, 32))  # 8 heads, 64 tokens, 32 dim
K = rng.random((8, 32, 64))
scores = Q @ K               # (8, 64, 64) — batch matmul!
print("Q",Q)
print("K",K)
print("Scores",scores)

Q [[[0.46241888 0.5218523  0.19226823 ... 0.26042136 0.17250647 0.94589404]
  [0.65576263 0.00498541 0.61338495 ... 0.05373171 0.73878246 0.3440084 ]
  [0.44068255 0.12817936 0.80101282 ... 0.56128143 0.02549128 0.20234505]
  ...
  [0.5789267  0.29626066 0.99514389 ... 0.01119178 0.4201754  0.98487147]
  [0.49206784 0.6876277  0.24544978 ... 0.41427184 0.76406608 0.77879337]
  [0.53383799 0.77204886 0.41046736 ... 0.24182585 0.07537176 0.41175004]]

 [[0.97747922 0.55085513 0.67121232 ... 0.92790202 0.17029684 0.22732586]
  [0.30219343 0.26613498 0.39169642 ... 0.70773176 0.46321674 0.67739652]
  [0.91163108 0.59054089 0.99419991 ... 0.08938608 0.62813443 0.8096807 ]
  ...
  [0.25454245 0.6331601  0.71942797 ... 0.97078839 0.94843225 0.19912122]
  [0.93498298 0.49001719 0.4336882  ... 0.76159961 0.0065808  0.70572694]
  [0.89626249 0.80389608 0.87552561 ... 0.08666953 0.96319896 0.15196156]]

 [[0.2690682  0.12636834 0.51302139 ... 0.58578785 0.46711871 0.97778438]
  [0.94715361 0.1171

In [84]:
# einsum — trace of matrix product
np.einsum('ij,ji->', A, A.T)  # scalar: trace(A Aᵀ)

np.float64(5.040258567192636)

In [85]:
A

array([[0.27422816, 0.31791214, 0.13776071, 0.53257416],
       [0.9003258 , 0.9783281 , 0.90462313, 0.96262492],
       [0.32295309, 0.4828968 , 0.61092627, 0.58133899]])